export type DailyPoem = {
  line: string;
  author: string;
};

export type DailySentence = {
  en: string;
  zh: string;
  from: string;
};

export const DAILY_POEMS: DailyPoem[] = [
  { line: "兴尽悲来，识盈虚之有数。", author: "王勃" },
  { line: "我未成名君未嫁，可能俱是不如人。", author: "罗隐" },
  { line: "老当益壮，宁移白首之心？穷且益坚，不坠青云之志。", author: "王勃" },
  { line: "时运不齐，命途多舛。冯唐易老，李广难封。", author: "王勃" },
  { line: "东隅已逝，桑榆非晚。", author: "王勃" },
  { line: "北海虽赊，扶摇可接。", author: "王勃" },
  { line: "关山难越，谁悲失路之人；萍水相逢，尽是他乡之客。", author: "王勃" },
  { line: "酌贪泉而觉爽，处涸辙以犹欢。", author: "王勃" },
  { line: "无路请缨，等终军之弱冠；有怀投笔，慕宗悫之长风。", author: "王勃" },
  { line: "落霞与孤鹜齐飞，秋水共长天一色。", author: "王勃" },
  { line: "天行健，君子以自强不息。", author: "周易" },
  { line: "路漫漫其修远兮，吾将上下而求索。", author: "屈原" },
  { line: "亦余心之所善兮，虽九死其犹未悔。", author: "屈原" },
  { line: "举世皆浊我独清，众人皆醉我独醒。", author: "屈原" },
  { line: "自反而缩，虽千万人吾往矣。", author: "孟子" },
  { line: "故天将降大任于是人也，必先苦其心志，劳其筋骨。", author: "孟子" },
  { line: "富贵不能淫，贫贱不能移，威武不能屈。", author: "孟子" },
  { line: "士不可以不弘毅，任重而道远。", author: "论语" },
  { line: "三军可夺帅也，匹夫不可夺志也。", author: "论语" },
  { line: "知其不可而为之。", author: "论语" },
  { line: "燕雀安知鸿鹄之志哉。", author: "史记" },
  { line: "王侯将相宁有种乎。", author: "史记" },
  { line: "风萧萧兮易水寒，壮士一去兮不复还。", author: "战国策" },
  { line: "力拔山兮气盖世，时不利兮骓不逝。", author: "项羽" },
  { line: "老骥伏枥，志在千里；烈士暮年，壮心不已。", author: "曹操" },
  { line: "对酒当歌，人生几何？譬如朝露，去日苦多。", author: "曹操" },
  { line: "前不见古人，后不见来者。念天地之悠悠，独怆然而涕下。", author: "陈子昂" },
  { line: "仰天大笑出门去，我辈岂是蓬蒿人。", author: "李白" },
  { line: "大鹏一日同风起，扶摇直上九万里。", author: "李白" },
  { line: "俱怀逸兴壮思飞，欲上青天揽明月。", author: "李白" },
  { line: "安能摧眉折腰事权贵，使我不得开心颜。", author: "李白" },
  { line: "长风破浪会有时，直挂云帆济沧海。", author: "李白" },
  { line: "天生我材必有用，千金散尽还复来。", author: "李白" },
  { line: "出师未捷身先死，长使英雄泪满襟。", author: "杜甫" },
  { line: "会当凌绝顶，一览众山小。", author: "杜甫" },
  { line: "莫愁前路无知己，天下谁人不识君。", author: "高适" },
  { line: "黄沙百战穿金甲，不破楼兰终不还。", author: "王昌龄" },
  { line: "男儿何不带吴钩，收取关山五十州。", author: "李贺" },
  { line: "宁为百夫长，胜作一书生。", author: "杨炯" },
  { line: "十年磨一剑，霜刃未曾试。", author: "贾岛" },
  { line: "江东子弟多才俊，卷土重来未可知。", author: "杜牧" },
  { line: "沉舟侧畔千帆过，病树前头万木春。", author: "刘禹锡" },
  { line: "千淘万漉虽辛苦，吹尽狂沙始到金。", author: "刘禹锡" },
  { line: "先天下之忧而忧，后天下之乐而乐。", author: "范仲淹" },
  { line: "大江东去，浪淘尽，千古风流人物。", author: "苏轼" },
  { line: "一点浩然气，千里快哉风。", author: "苏轼" },
  { line: "竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。", author: "苏轼" },
  { line: "回首向来萧瑟处，归去，也无风雨也无晴。", author: "苏轼" },
  { line: "寄蜉蝣于天地，渺沧海之一粟。", author: "苏轼" },
  { line: "古之立大事者，不惟有超世之才，亦必有坚忍不拔之志。", author: "苏轼" },
  { line: "谁道人生无再少？门前流水尚能西。", author: "苏轼" },
  { line: "不识庐山真面目，只缘身在此山中。", author: "苏轼" },
  { line: "想当年，金戈铁马，气吞万里如虎。", author: "辛弃疾" },
  { line: "了却君王天下事，赢得生前身后名。可怜白发生！", author: "辛弃疾" },
  { line: "醉里挑灯看剑，梦回吹角连营。", author: "辛弃疾" },
  { line: "青山遮不住，毕竟东流去。", author: "辛弃疾" },
  { line: "凭谁问：廉颇老矣，尚能饭否？", author: "辛弃疾" },
  { line: "天下英雄谁敌手？曹刘。生子当如孙仲谋。", author: "辛弃疾" },
  { line: "生当作人杰，死亦为鬼雄。", author: "李清照" },
  { line: "至今思项羽，不肯过江东。", author: "李清照" },
  { line: "莫等闲，白了少年头，空悲切。", author: "岳飞" },
  { line: "三十功名尘与土，八千里路云和月。", author: "岳飞" },
  { line: "待从头、收拾旧山河，朝天阙。", author: "岳飞" },
  { line: "人生自古谁无死，留取丹心照汗青。", author: "文天祥" },
  { line: "天地有正气，杂然赋流形。", author: "文天祥" },
  { line: "位卑未敢忘忧国。", author: "陆游" },
  { line: "夜阑卧听风吹雨，铁马冰河入梦来。", author: "陆游" },
  { line: "僵卧孤村不自哀，尚思为国戍轮台。", author: "陆游" },
  { line: "楚虽三户能亡秦，岂有堂堂中国空无人。", author: "陆游" },
  { line: "壮心未与年俱老，死去犹能作鬼雄。", author: "陆游" },
  { line: "山重水复疑无路，柳暗花明又一村。", author: "陆游" },
  { line: "不畏浮云遮望眼，自缘身在最高层。", author: "王安石" },
  { line: "落红不是无情物，化作春泥更护花。", author: "龚自珍" },
  { line: "我劝天公重抖擞，不拘一格降人材。", author: "龚自珍" },
  { line: "我自横刀向天笑，去留肝胆两昆仑。", author: "谭嗣同" },
  { line: "苟利国家生死以，岂因祸福避趋之。", author: "林则徐" },
  { line: "粉骨碎身浑不怕，要留清白在人间。", author: "于谦" },
  { line: "千磨万击还坚劲，任尔东西南北风。", author: "郑燮" },
  { line: "此心光明，亦复何言。", author: "王阳明" },
  { line: "破山中贼易，破心中贼难。", author: "王阳明" },
  { line: "横眉冷对千夫指，俯首甘为孺子牛。", author: "鲁迅" },
  { line: "寄意寒星荃不察，我以我血荐轩辕。", author: "鲁迅" },
  { line: "雄关漫道真如铁，而今迈步从头越。", author: "毛泽东" },
  { line: "问苍茫大地，谁主沉浮？", author: "毛泽东" },
  { line: "俱往矣，数风流人物，还看今朝。", author: "毛泽东" },
  { line: "自信人生二百年，会当水击三千里。", author: "毛泽东" },
  { line: "面壁十年图破壁，难酬蹈海亦英雄。", author: "周恩来" },
  { line: "行到水穷处，坐看云起时。", author: "王维" },
  { line: "后之视今，亦犹今之视昔。", author: "王羲之" },
  { line: "天下兴亡，匹夫有责。", author: "顾炎武" },
  { line: "岂曰无衣？与子同袍。", author: "诗经" },
  { line: "醉卧沙场君莫笑，古来征战几人回。", author: "王翰" },
  { line: "秦时明月汉时关，万里长征人未还。", author: "王昌龄" },
  { line: "事了拂衣去，深藏身与名。", author: "李白" },
  { line: "抽刀断水水更流，举杯消愁愁更愁。", author: "李白" },
  { line: "哀吾生之须臾，羡长江之无穷。", author: "苏轼" },
  { line: "乱石穿空，惊涛拍岸，卷起千堆雪。", author: "苏轼" },
  { line: "马作的卢飞快，弓如霹雳弦惊。", author: "辛弃疾" },
  { line: "零落成泥碾作尘，只有香如故。", author: "陆游" },
  { line: "纸上得来终觉浅，绝知此事要躬行。", author: "陆游" },
  { line: "床前明月光，疑是地上霜。", author: "李白" },
  { line: "举头望明月，低头思故乡。", author: "李白" },
  { line: "飞流直下三千尺，疑是银河落九天。", author: "李白" },
  { line: "两岸猿声啼不住，轻舟已过万重山。", author: "李白" },
  { line: "桃花潭水深千尺，不及汪伦送我情。", author: "李白" },
  { line: "孤帆远影碧空尽，唯见长江天际流。", author: "李白" },
  { line: "君不见黄河之水天上来，奔流到海不复回。", author: "李白" },
  { line: "云想衣裳花想容，春风拂槛露华浓。", author: "李白" },
  { line: "山随平野尽，江入大荒流。", author: "李白" },
  { line: "春眠不觉晓，处处闻啼鸟。", author: "孟浩然" },
  { line: "夜来风雨声，花落知多少。", author: "孟浩然" },
  { line: "白日依山尽，黄河入海流。", author: "王之涣" },
  { line: "欲穷千里目，更上一层楼。", author: "王之涣" },
  { line: "黄河远上白云间，一片孤城万仞山。", author: "王之涣" },
  { line: "羌笛何须怨杨柳，春风不度玉门关。", author: "王之涣" },
  { line: "空山新雨后，天气晚来秋。", author: "王维" },
  { line: "明月松间照，清泉石上流。", author: "王维" },
  { line: "独在异乡为异客，每逢佳节倍思亲。", author: "王维" },
  { line: "劝君更尽一杯酒，西出阳关无故人。", author: "王维" },
  { line: "大漠孤烟直，长河落日圆。", author: "王维" },
  { line: "海内存知己，天涯若比邻。", author: "王勃" },
  { line: "海上生明月，天涯共此时。", author: "张九龄" },
  { line: "少小离家老大回，乡音无改鬓毛衰。", author: "贺知章" },
  { line: "儿童相见不相识，笑问客从何处来。", author: "贺知章" },
  { line: "谁知盘中餐，粒粒皆辛苦。", author: "李绅" },
  { line: "千山鸟飞绝，万径人踪灭。", author: "柳宗元" },
  { line: "孤舟蓑笠翁，独钓寒江雪。", author: "柳宗元" },
  { line: "国破山河在，城春草木深。", author: "杜甫" },
  { line: "感时花溅泪，恨别鸟惊心。", author: "杜甫" },
  { line: "烽火连三月，家书抵万金。", author: "杜甫" },
  { line: "两个黄鹂鸣翠柳，一行白鹭上青天。", author: "杜甫" },
  { line: "窗含西岭千秋雪，门泊东吴万里船。", author: "杜甫" },
  { line: "无边落木萧萧下，不尽长江滚滚来。", author: "杜甫" },
  { line: "安得广厦千万间，大庇天下寒士俱欢颜。", author: "杜甫" },
  { line: "朱门酒肉臭，路有冻死骨。", author: "杜甫" },
  { line: "野火烧不尽，春风吹又生。", author: "白居易" },
  { line: "同是天涯沦落人，相逢何必曾相识。", author: "白居易" },
  { line: "在天愿作比翼鸟，在地愿为连理枝。", author: "白居易" },
  { line: "别有幽愁暗恨生，此时无声胜有声。", author: "白居易" },
  { line: "几处早莺争暖树，谁家新燕啄春泥。", author: "白居易" },
  { line: "洛阳亲友如相问，一片冰心在玉壶。", author: "王昌龄" },
  { line: "但使龙城飞将在，不教胡马度阴山。", author: "王昌龄" },
  { line: "黄鹤一去不复返，白云千载空悠悠。", author: "崔颢" },
  { line: "日暮乡关何处是？烟波江上使人愁。", author: "崔颢" },
  { line: "月落乌啼霜满天，江枫渔火对愁眠。", author: "张继" },
  { line: "姑苏城外寒山寺，夜半钟声到客船。", author: "张继" },
  { line: "谁言寸草心，报得三春晖。", author: "孟郊" },
  { line: "春风得意马蹄疾，一日看尽长安花。", author: "孟郊" },
  { line: "鸟宿池边树，僧敲月下门。", author: "贾岛" },
  { line: "停车坐爱枫林晚，霜叶红于二月花。", author: "杜牧" },
  { line: "商女不知亡国恨，隔江犹唱后庭花。", author: "杜牧" },
  { line: "清明时节雨纷纷，路上行人欲断魂。", author: "杜牧" },
  { line: "二十四桥明月夜，玉人何处教吹箫。", author: "杜牧" },
  { line: "东风不与周郎便，铜雀春深锁二乔。", author: "杜牧" },
  { line: "春蚕到死丝方尽，蜡炬成灰泪始干。", author: "李商隐" },
  { line: "夕阳无限好，只是近黄昏。", author: "李商隐" },
  { line: "此情可待成追忆，只是当时已惘然。", author: "李商隐" },
  { line: "何当共剪西窗烛，却话巴山夜雨时。", author: "李商隐" },
  { line: "相见时难别亦难，东风无力百花残。", author: "李商隐" },
  { line: "庄生晓梦迷蝴蝶，望帝春心托杜鹃。", author: "李商隐" },
  { line: "问君能有几多愁？恰似一江春水向东流。", author: "李煜" },
  { line: "剪不断，理还乱，是离愁。", author: "李煜" },
  { line: "流水落花春去也，天上人间。", author: "李煜" },
  { line: "春花秋月何时了，往事知多少。", author: "李煜" },
  { line: "多情自古伤离别，更那堪冷落清秋节。", author: "柳永" },
  { line: "今宵酒醒何处？杨柳岸，晓风残月。", author: "柳永" },
  { line: "衣带渐宽终不悔，为伊消得人憔悴。", author: "柳永" },
  { line: "无可奈何花落去，似曾相识燕归来。", author: "晏殊" },
  { line: "两情若是久长时，又岂在朝朝暮暮。", author: "秦观" },
  { line: "但愿人长久，千里共婵娟。", author: "苏轼" },
  { line: "人有悲欢离合，月有阴晴圆缺。", author: "苏轼" },
  { line: "十年生死两茫茫，不思量，自难忘。", author: "苏轼" },
  { line: "欲把西湖比西子，淡妆浓抹总相宜。", author: "苏轼" },
  { line: "日啖荔枝三百颗，不辞长作岭南人。", author: "苏轼" },
  { line: "众里寻他千百度，蓦然回首，那人却在灯火阑珊处。", author: "辛弃疾" },
  { line: "稻花香里说丰年，听取蛙声一片。", author: "辛弃疾" },
  { line: "最喜小儿亡赖，溪头卧剥莲蓬。", author: "辛弃疾" },
  { line: "寻寻觅觅，冷冷清清，凄凄惨惨戚戚。", author: "李清照" },
  { line: "知否，知否？应是绿肥红瘦。", author: "李清照" },
  { line: "此情无计可消除，才下眉头，却上心头。", author: "李清照" },
  { line: "问渠那得清如许？为有源头活水来。", author: "朱熹" },
  { line: "小荷才露尖尖角，早有蜻蜓立上头。", author: "杨万里" },
  { line: "接天莲叶无穷碧，映日荷花别样红。", author: "杨万里" },
  { line: "王师北定中原日，家祭无忘告乃翁。", author: "陆游" },
  { line: "小楼一夜听春雨，深巷明朝卖杏花。", author: "陆游" },
  { line: "采菊东篱下，悠然见南山。", author: "陶渊明" },
  { line: "问君何能尔？心远地自偏。", author: "陶渊明" },
  { line: "羁鸟恋旧林，池鱼思故渊。", author: "陶渊明" },
  { line: "月明星稀，乌鹊南飞。", author: "曹操" },
  { line: "山不厌高，海不厌深。", author: "曹操" },
  { line: "本是同根生，相煎何太急。", author: "曹植" },
  { line: "旧时王谢堂前燕，飞入寻常百姓家。", author: "刘禹锡" },
  { line: "山不在高，有仙则名。", author: "刘禹锡" },
  { line: "水不在深，有龙则灵。", author: "刘禹锡" },
  { line: "业精于勤，荒于嬉；行成于思，毁于随。", author: "韩愈" },
  { line: "世有伯乐，然后有千里马。", author: "韩愈" },
  { line: "出淤泥而不染，濯清涟而不妖。", author: "周敦颐" },
  { line: "鞠躬尽瘁，死而后已。", author: "诸葛亮" },
  { line: "非淡泊无以明志，非宁静无以致远。", author: "诸葛亮" },
  { line: "亲贤臣，远小人。", author: "诸葛亮" },
  { line: "关关雎鸠，在河之洲。窈窕淑女，君子好逑。", author: "诗经" },
  { line: "蒹葭苍苍，白露为霜。所谓伊人，在水一方。", author: "诗经" },
  { line: "执子之手，与子偕老。", author: "诗经" },
  { line: "青青子衿，悠悠我心。", author: "诗经" },
  { line: "投我以木桃，报之以琼瑶。", author: "诗经" },
  { line: "昔我往矣，杨柳依依。今我来思，雨雪霏霏。", author: "诗经" },
  { line: "愿得一心人，白头不相离。", author: "汉乐府" },
  { line: "少壮不努力，老大徒伤悲。", author: "汉乐府" },
  { line: "人生天地间，忽如远行客。", author: "古诗十九首" },
  { line: "忽如一夜春风来，千树万树梨花开。", author: "岑参" },
  { line: "春江潮水连海平，海上明月共潮生。", author: "张若虚" },
  { line: "江畔何人初见月？江月何年初照人？", author: "张若虚" },
  { line: "人生代代无穷已，江月年年只相似。", author: "张若虚" },
  { line: "月上柳梢头，人约黄昏后。", author: "欧阳修" },
  { line: "泪眼问花花不语，乱红飞过秋千去。", author: "欧阳修" },
  { line: "庭院深深深几许，杨柳堆烟，帘幕无重数。", author: "欧阳修" },
  { line: "醉翁之意不在酒，在乎山水之间也。", author: "欧阳修" },
  { line: "空山不见人，但闻人语响。", author: "王维" },
  { line: "返景入深林，复照青苔上。", author: "王维" },
  { line: "渭城朝雨浥轻尘，客舍青青柳色新。", author: "王维" },
  { line: "红豆生南国，春来发几枝。", author: "王维" },
  { line: "愿君多采撷，此物最相思。", author: "王维" },
  { line: "江流天地外，山色有无中。", author: "王维" },
  { line: "竹喧归浣女，莲动下渔舟。", author: "王维" },
  { line: "故人西辞黄鹤楼，烟花三月下扬州。", author: "李白" },
  { line: "举杯邀明月，对影成三人。", author: "李白" },
  { line: "众鸟高飞尽，孤云独去闲。", author: "李白" },
  { line: "相看两不厌，只有敬亭山。", author: "李白" },
  { line: "小时不识月，呼作白玉盘。", author: "李白" },
  { line: "今人不见古时月，今月曾经照古人。", author: "李白" },
  { line: "燕草如碧丝，秦桑低绿枝。", author: "李白" },
  { line: "危楼高百尺，手可摘星辰。", author: "李白" },
  { line: "好雨知时节，当春乃发生。", author: "杜甫" },
  { line: "随风潜入夜，润物细无声。", author: "杜甫" },
  { line: "造化钟神秀，阴阳割昏晓。", author: "杜甫" },
  { line: "星垂平野阔，月涌大江流。", author: "杜甫" },
  { line: "读书破万卷，下笔如有神。", author: "杜甫" },
  { line: "露从今夜白，月是故乡明。", author: "杜甫" },
  { line: "细雨鱼儿出，微风燕子斜。", author: "杜甫" },
  { line: "日出江花红胜火，春来江水绿如蓝。", author: "白居易" },
  { line: "江南好，风景旧曾谙。", author: "白居易" },
  { line: "乱花渐欲迷人眼，浅草才能没马蹄。", author: "白居易" },
  { line: "一道残阳铺水中，半江瑟瑟半江红。", author: "白居易" },
  { line: "东边日出西边雨，道是无晴却有晴。", author: "刘禹锡" },
  { line: "山明水净夜来霜，数树深红出浅黄。", author: "刘禹锡" },
  { line: "怀旧空吟闻笛赋，到乡翻似烂柯人。", author: "刘禹锡" },
  { line: "千里莺啼绿映红，水村山郭酒旗风。", author: "杜牧" },
  { line: "南朝四百八十寺，多少楼台烟雨中。", author: "杜牧" },
  { line: "远上寒山石径斜，白云生处有人家。", author: "杜牧" },
  { line: "锦瑟无端五十弦，一弦一柱思华年。", author: "李商隐" },
  { line: "沧海月明珠有泪，蓝田日暖玉生烟。", author: "李商隐" },
  { line: "身无彩凤双飞翼，心有灵犀一点通。", author: "李商隐" },
  { line: "天街小雨润如酥，草色遥看近却无。", author: "韩愈" },
  { line: "云横秦岭家何在？雪拥蓝关马不前。", author: "韩愈" },
  { line: "春潮带雨晚来急，野渡无人舟自横。", author: "韦应物" },
  { line: "独怜幽草涧边生，上有黄鹂深树鸣。", author: "韦应物" },
  { line: "西塞山前白鹭飞，桃花流水鳜鱼肥。", author: "张志和" },
  { line: "青箬笠，绿蓑衣，斜风细雨不须归。", author: "张志和" },
  { line: "海日生残夜，江春入旧年。", author: "王湾" },
  { line: "客路青山外，行舟绿水前。", author: "王湾" },
  { line: "绿树村边合，青山郭外斜。", author: "孟浩然" },
  { line: "开轩面场圃，把酒话桑麻。", author: "孟浩然" },
  { line: "气蒸云梦泽，波撼岳阳城。", author: "孟浩然" },
  { line: "故人具鸡黍，邀我至田家。", author: "孟浩然" },
  { line: "日暮苍山远，天寒白屋贫。", author: "刘长卿" },
  { line: "柴门闻犬吠，风雪夜归人。", author: "刘长卿" },
  { line: "鸡声茅店月，人迹板桥霜。", author: "温庭筠" },
  { line: "过尽千帆皆不是，斜晖脉脉水悠悠。", author: "温庭筠" },
  { line: "小山重叠金明灭，鬓云欲度香腮雪。", author: "温庭筠" },
  { line: "枯藤老树昏鸦，小桥流水人家。", author: "马致远" },
  { line: "夕阳西下，断肠人在天涯。", author: "马致远" },
  { line: "兴，百姓苦；亡，百姓苦。", author: "张养浩" },
  { line: "峰峦如聚，波涛如怒，山河表里潼关路。", author: "张养浩" },
  { line: "碧云天，黄叶地，秋色连波，波上寒烟翠。", author: "范仲淹" },
  { line: "塞下秋来风景异，衡阳雁去无留意。", author: "范仲淹" },
  { line: "浊酒一杯家万里，燕然未勒归无计。", author: "范仲淹" },
  { line: "春风又绿江南岸，明月何时照我还。", author: "王安石" },
  { line: "爆竹声中一岁除，春风送暖入屠苏。", author: "王安石" },
  { line: "水光潋滟晴方好，山色空蒙雨亦奇。", author: "苏轼" },
  { line: "竹外桃花三两枝，春江水暖鸭先知。", author: "苏轼" },
  { line: "荷尽已无擎雨盖，菊残犹有傲霜枝。", author: "苏轼" },
  { line: "人生若只如初见，何事秋风悲画扇。", author: "纳兰性德" },
  { line: "当时只道是寻常。", author: "纳兰性德" },
  { line: "行行重行行，与君生别离。", author: "古诗十九首" },
  { line: "思君令人老，岁月忽已晚。", author: "古诗十九首" },
  { line: "胡马依北风，越鸟巢南枝。", author: "古诗十九首" },
  { line: "盈盈一水间，脉脉不得语。", author: "古诗十九首" },
  { line: "江南可采莲，莲叶何田田。", author: "汉乐府" },
  { line: "青青河畔草，绵绵思远道。", author: "汉乐府" },
  { line: "山无陵，江水为竭，冬雷震震，夏雨雪，天地合，乃敢与君绝。", author: "汉乐府" },
  { line: "北方有佳人，绝世而独立。", author: "李延年" },
  { line: "一顾倾人城，再顾倾人国。", author: "李延年" },
  { line: "劝君莫惜金缕衣，劝君惜取少年时。", author: "杜秋娘" },
  { line: "花开堪折直须折，莫待无花空折枝。", author: "杜秋娘" },
  { line: "碧玉妆成一树高，万条垂下绿丝绦。", author: "贺知章" },
  { line: "不知细叶谁裁出，二月春风似剪刀。", author: "贺知章" },
  { line: "咬定青山不放松，立根原在破岩中。", author: "郑燮" },
  { line: "不要人夸颜色好，只留清气满乾坤。", author: "王冕" },
  { line: "墙角数枝梅，凌寒独自开。", author: "王安石" },
  { line: "遥知不是雪，为有暗香来。", author: "王安石" },
  { line: "梅须逊雪三分白，雪却输梅一段香。", author: "卢梅坡" },
  { line: "等闲识得东风面，万紫千红总是春。", author: "朱熹" },
  { line: "胜日寻芳泗水滨，无边光景一时新。", author: "朱熹" },
  { line: "儿童散学归来早，忙趁东风放纸鸢。", author: "高鼎" },
  { line: "草长莺飞二月天，拂堤杨柳醉春烟。", author: "高鼎" },
  { line: "黄梅时节家家雨，青草池塘处处蛙。", author: "赵师秀" },
  { line: "有约不来过夜半，闲敲棋子落灯花。", author: "赵师秀" },
  { line: "小娃撑小艇，偷采白莲回。", author: "白居易" },
  { line: "不解藏踪迹，浮萍一道开。", author: "白居易" },
  { line: "牧童骑黄牛，歌声振林樾。", author: "袁枚" },
  { line: "意欲捕鸣蝉，忽然闭口立。", author: "袁枚" },
  { line: "毕竟西湖六月中，风光不与四时同。", author: "杨万里" },
  { line: "泉眼无声惜细流，树阴照水爱晴柔。", author: "杨万里" },
  { line: "试问闲愁都几许？一川烟草，满城风絮，梅子黄时雨。", author: "贺铸" },
  { line: "落花人独立，微雨燕双飞。", author: "晏几道" },
  { line: "当时明月在，曾照彩云归。", author: "晏几道" },
  { line: "今宵剩把银釭照，犹恐相逢是梦中。", author: "晏几道" },
  { line: "沙上并禽池上暝，云破月来花弄影。", author: "张先" },
  { line: "三秋桂子，十里荷花。", author: "柳永" },
  { line: "怒发冲冠，凭栏处、潇潇雨歇。", author: "岳飞" },
  { line: "千古江山，英雄无觅孙仲谋处。", author: "辛弃疾" },
  { line: "舞榭歌台，风流总被雨打风吹去。", author: "辛弃疾" },
  { line: "斜阳草树，寻常巷陌，人道寄奴曾住。", author: "辛弃疾" },
  { line: "昨夜西风凋碧树，独上高楼，望尽天涯路。", author: "晏殊" },
  { line: "欲寄彩笺兼尺素，山长水阔知何处。", author: "晏殊" },
  { line: "昨夜星辰昨夜风，画楼西畔桂堂东。", author: "李商隐" },
  { line: "君问归期未有期，巴山夜雨涨秋池。", author: "李商隐" },
  { line: "春风十里扬州路，卷上珠帘总不如。", author: "杜牧" },
  { line: "十年一觉扬州梦，赢得青楼薄幸名。", author: "杜牧" },
  { line: "烟笼寒水月笼沙，夜泊秦淮近酒家。", author: "杜牧" },
  { line: "银烛秋光冷画屏，轻罗小扇扑流萤。", author: "杜牧" },
  { line: "天阶夜色凉如水，卧看牵牛织女星。", author: "杜牧" },
  { line: "长安回望绣成堆，山顶千门次第开。", author: "杜牧" },
  { line: "一骑红尘妃子笑，无人知是荔枝来。", author: "杜牧" },
  { line: "葡萄美酒夜光杯，欲饮琵琶马上催。", author: "王翰" },
  { line: "青海长云暗雪山，孤城遥望玉门关。", author: "王昌龄" },
  { line: "烽火城西百尺楼，黄昏独坐海风秋。", author: "王昌龄" },
  { line: "大漠风尘日色昏，红旗半卷出辕门。", author: "王昌龄" },
  { line: "轮台东门送君去，去时雪满天山路。", author: "岑参" },
  { line: "山回路转不见君，雪上空留马行处。", author: "岑参" },
  { line: "北风卷地白草折，胡天八月即飞雪。", author: "岑参" },
  { line: "瀚海阑干百丈冰，愁云惨淡万里凝。", author: "岑参" },
  { line: "中军置酒饮归客，胡琴琵琶与羌笛。", author: "岑参" },
  { line: "千里黄云白日曛，北风吹雁雪纷纷。", author: "高适" },
  { line: "战士军前半死生，美人帐下犹歌舞。", author: "高适" },
  { line: "君不见走马川行雪海边，平沙莽莽黄入天。", author: "岑参" },
  { line: "月黑雁飞高，单于夜遁逃。", author: "卢纶" },
  { line: "欲将轻骑逐，大雪满弓刀。", author: "卢纶" },
  { line: "林暗草惊风，将军夜引弓。", author: "卢纶" },
  { line: "平明寻白羽，没在石棱中。", author: "卢纶" },
  { line: "慈母手中线，游子身上衣。", author: "孟郊" },
  { line: "临行密密缝，意恐迟迟归。", author: "孟郊" },
  { line: "松下问童子，言师采药去。", author: "贾岛" },
  { line: "只在此山中，云深不知处。", author: "贾岛" },
  { line: "两句三年得，一吟双泪流。", author: "贾岛" },
  { line: "移舟泊烟渚，日暮客愁新。", author: "孟浩然" },
  { line: "野旷天低树，江清月近人。", author: "孟浩然" },
  { line: "人事有代谢，往来成古今。", author: "孟浩然" },
  { line: "江山留胜迹，我辈复登临。", author: "孟浩然" },
  { line: "梧桐更兼细雨，到黄昏、点点滴滴。", author: "李清照" },
  { line: "莫道不销魂，帘卷西风，人比黄花瘦。", author: "李清照" },
  { line: "雁字回时，月满西楼。", author: "李清照" },
  { line: "花自飘零水自流，一种相思，两处闲愁。", author: "李清照" },
  { line: "物是人非事事休，欲语泪先流。", author: "李清照" },
  { line: "守着窗儿，独自怎生得黑。", author: "李清照" },
  { line: "若有人知春去处，唤取归来同住。", author: "黄庭坚" },
  { line: "桃李春风一杯酒，江湖夜雨十年灯。", author: "黄庭坚" },
  { line: "我住长江头，君住长江尾。", author: "李之仪" },
  { line: "日日思君不见君，共饮长江水。", author: "李之仪" },
  { line: "此水几时休，此恨何时已。", author: "李之仪" },
  { line: "只愿君心似我心，定不负相思意。", author: "李之仪" },
  { line: "我见青山多妩媚，料青山见我应如是。", author: "辛弃疾" },
  { line: "七八个星天外，两三点雨山前。", author: "辛弃疾" },
  { line: "明月别枝惊鹊，清风半夜鸣蝉。", author: "辛弃疾" },
  { line: "旧时茅店社林边，路转溪桥忽见。", author: "辛弃疾" },
  { line: "少年不识愁滋味，爱上层楼。", author: "辛弃疾" },
  { line: "而今识尽愁滋味，欲说还休。", author: "辛弃疾" },
  { line: "人生得意须尽欢，莫使金樽空对月。", author: "李白" },
  { line: "烹羊宰牛且为乐，会须一饮三百杯。", author: "李白" },
  { line: "岑夫子，丹丘生，将进酒，杯莫停。", author: "李白" },
  { line: "古来圣贤皆寂寞，惟有饮者留其名。", author: "李白" },
  { line: "五花马，千金裘，呼儿将出换美酒。", author: "李白" },
  { line: "与尔同销万古愁。", author: "李白" },
];

export const DAILY_SENTENCES: DailySentence[] = [
  {
    en: "I am the master of my fate: I am the captain of my soul.",
    zh: "我是命运的主宰，我是灵魂的船长。",
    from: "Invictus",
  },
  {
    en: "The fault, dear Brutus, is not in our stars, but in ourselves.",
    zh: "亲爱的布鲁图，错不在星辰，而在我们自己。",
    from: "莎士比亚",
  },
  {
    en: "Cowards die many times before their deaths; the valiant never taste of death but once.",
    zh: "懦夫未死已死过千回；勇者一生只死一回。",
    from: "莎士比亚",
  },
  {
    en: "There is a tide in the affairs of men which, taken at the flood, leads on to fortune.",
    zh: "人事亦有潮汐，乘涨而起，便可通达。",
    from: "莎士比亚",
  },
  {
    en: "What's past is prologue.",
    zh: "既往只是序章。",
    from: "莎士比亚",
  },
  {
    en: "We are such stuff as dreams are made on.",
    zh: "我们都是梦的质料做成的。",
    from: "莎士比亚",
  },
  {
    en: "Do not go gentle into that good night. Rage, rage against the dying of the light.",
    zh: "莫温顺走入那良夜。怒吼吧，怒吼着对抗熄灭的光。",
    from: "迪伦·托马斯",
  },
  {
    en: "He who has a why to live can bear almost any how.",
    zh: "人只要有为何而活，几乎就能承受任何如何去活。",
    from: "尼采",
  },
  {
    en: "What does not kill me makes me stronger.",
    zh: "凡不能毁灭我的，必使我更强。",
    from: "尼采",
  },
  {
    en: "In the midst of winter, I found there was, within me, an invincible summer.",
    zh: "隆冬之中，我发现自己体内有一个不可战胜的夏天。",
    from: "加缪",
  },
  {
    en: "One must imagine Sisyphus happy.",
    zh: "必须想象西西弗斯是幸福的。",
    from: "加缪",
  },
  {
    en: "The struggle itself toward the heights is enough to fill a man's heart.",
    zh: "向着高峰的搏斗本身，已足以填满一颗心。",
    from: "加缪",
  },
  {
    en: "The unexamined life is not worth living.",
    zh: "未经省察的人生，不值得过。",
    from: "苏格拉底",
  },
  {
    en: "Fortune favors the bold.",
    zh: "命运偏爱勇者。",
    from: "维吉尔",
  },
  {
    en: "You have power over your mind — not outside events. Realize this, and you will find strength.",
    zh: "你能主宰的是内心，不是世事。明白这一点，便有了力量。",
    from: "马可·奥勒留",
  },
  {
    en: "Waste no more time arguing about what a good man should be. Be one.",
    zh: "别再争论好人该是什么样。去做一个。",
    from: "马可·奥勒留",
  },
  {
    en: "The impediment to action advances action. What stands in the way becomes the way.",
    zh: "挡路的东西，会把路推向前。障碍即是道路。",
    from: "马可·奥勒留",
  },
  {
    en: "If you're going through hell, keep going.",
    zh: "既已身在地狱，就别停下。",
    from: "丘吉尔",
  },
  {
    en: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    zh: "成功不是终点，失败也不是末日；真正要紧的，是继续走下去的勇气。",
    from: "丘吉尔",
  },
  {
    en: "Never give in — never, never, never.",
    zh: "永不屈服。永不，永不，永不。",
    from: "丘吉尔",
  },
  {
    en: "It always seems impossible until it's done.",
    zh: "凡事在做成之前，都像不可能。",
    from: "曼德拉",
  },
  {
    en: "Courage is not the absence of fear, but the triumph over it.",
    zh: "勇气不是没有恐惧，而是战胜恐惧。",
    from: "曼德拉",
  },
  {
    en: "A man can be destroyed but not defeated.",
    zh: "人可以被毁灭，但不能被打败。",
    from: "海明威",
  },
  {
    en: "The world breaks everyone, and afterward, many are strong at the broken places.",
    zh: "这世界会把每个人打碎；而后，许多人在裂处变得更硬。",
    from: "海明威",
  },
  {
    en: "We are all in the gutter, but some of us are looking at the stars.",
    zh: "我们都躺在阴沟里，但有人仍在仰望星空。",
    from: "王尔德",
  },
  {
    en: "To live is the rarest thing in the world. Most people exist, that is all.",
    zh: "活着是世上最稀有的事。多数人只是存在着。",
    from: "王尔德",
  },
  {
    en: "The only way out is through.",
    zh: "唯一的出路，是穿过它。",
    from: "弗罗斯特",
  },
  {
    en: "In three words I can sum up everything I've learned about life: it goes on.",
    zh: "关于人生，我只用三个词就能说完：它还在继续。",
    from: "弗罗斯特",
  },
  {
    en: "Do I dare disturb the universe?",
    zh: "我可敢惊扰这宇宙？",
    from: "艾略特",
  },
  {
    en: "That the powerful play goes on, and you may contribute a verse.",
    zh: "雄浑的戏还在演，而你也可以添上一句诗。",
    from: "惠特曼",
  },
  {
    en: "Carpe diem. Seize the day, boys. Make your lives extraordinary.",
    zh: "把握今天。让你们的生命变得非凡。",
    from: "死亡诗社",
  },
  {
    en: "We don't read and write poetry because it's cute. We read and write poetry because we are members of the human race.",
    zh: "我们读诗写诗，不是因为它可爱，而是因为我们是人类。",
    from: "死亡诗社",
  },
  {
    en: "What we do in life echoes in eternity.",
    zh: "我们此生所为，会在永恒里回响。",
    from: "角斗士",
  },
  {
    en: "Every man dies, not every man really lives.",
    zh: "人皆有一死，却并非人人真正活过。",
    from: "勇敢的心",
  },
  {
    en: "Hope is a good thing, maybe the best of things, and no good thing ever dies.",
    zh: "希望是好东西，也许是最好的东西，好东西是不会死的。",
    from: "肖申克的救赎",
  },
  {
    en: "Get busy living, or get busy dying.",
    zh: "要么忙着活，要么忙着死。",
    from: "肖申克的救赎",
  },
  {
    en: "All we have to decide is what to do with the time that is given us.",
    zh: "我们真正要决定的，只是如何使用被赋予的时光。",
    from: "指环王",
  },
  {
    en: "Even darkness must pass. A new day will come.",
    zh: "再深的黑暗也会过去。新的一天总会到来。",
    from: "指环王",
  },
  {
    en: "There's some good in this world, Mr. Frodo, and it's worth fighting for.",
    zh: "这世上仍有美好，弗罗多先生，值得我们为之而战。",
    from: "指环王",
  },
  {
    en: "Not all those who wander are lost.",
    zh: "流浪的人，未必迷失。",
    from: "托尔金",
  },
  {
    en: "I must not fear. Fear is the mind-killer.",
    zh: "我不可恐惧。恐惧是心灵的杀手。",
    from: "沙丘",
  },
  {
    en: "It is not the mountain we conquer, but ourselves.",
    zh: "我们征服的从来不是山，而是自己。",
    from: "希拉里",
  },
  {
    en: "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.",
    zh: "要紧的不是你能打多重，而是你能挨多重，还能继续向前。",
    from: "洛基",
  },
  {
    en: "Why do we fall, sir? So that we can learn to pick ourselves up.",
    zh: "我们为何跌倒？好学会自己站起来。",
    from: "蝙蝠侠",
  },
  {
    en: "You either die a hero, or you live long enough to see yourself become the villain.",
    zh: "要么当英雄而死，要么活得够久，眼看自己变成恶棍。",
    from: "黑暗骑士",
  },
  {
    en: "It is our choices that show what we truly are, far more than our abilities.",
    zh: "真正说明我们是谁的，是选择，远胜过才能。",
    from: "哈利·波特",
  },
  {
    en: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
    zh: "即便在最黑暗的岁月，幸福也找得到，只要记得去开灯。",
    from: "哈利·波特",
  },
  {
    en: "Dark and difficult times lie ahead. Soon we must all face the choice between what is right and what is easy.",
    zh: "艰难时日在前。很快我们都得在正确与容易之间做选择。",
    from: "哈利·波特",
  },
  {
    en: "Never forget what you are. The rest of the world will not. Wear it like armor, and it can never be used to hurt you.",
    zh: "别忘了你是什么。世人不会忘。把它当铠甲穿上，便再也伤不到你。",
    from: "权力的游戏",
  },
  {
    en: "Can a man still be brave if he's afraid? That is the only time a man can be brave.",
    zh: "人害怕时还能勇敢吗？那恰恰是唯一能勇敢的时刻。",
    from: "权力的游戏",
  },
  {
    en: "Chaos isn't a pit. Chaos is a ladder.",
    zh: "混乱不是深渊。混乱是一架梯子。",
    from: "权力的游戏",
  },
  {
    en: "All those moments will be lost in time, like tears in rain.",
    zh: "所有这些瞬间，都会消失在时光里，如同泪水没入雨中。",
    from: "银翼杀手",
  },
  {
    en: "Do. Or do not. There is no try.",
    zh: "做，或者不做。没有试试看。",
    from: "星球大战",
  },
  {
    en: "The cave you fear to enter holds the treasure you seek.",
    zh: "你不敢踏入的洞穴，藏着你要找的宝物。",
    from: "坎贝尔",
  },
  {
    en: "Life shrinks or expands in proportion to one's courage.",
    zh: "生命随勇气收缩，也随勇气张开。",
    from: "阿娜伊斯·宁",
  },
  {
    en: "You were born with wings, why prefer to crawl through life?",
    zh: "你生来有翅膀，何必一辈子爬着过？",
    from: "鲁米",
  },
  {
    en: "As you start to walk on the way, the way appears.",
    zh: "你一迈步上路，路便显现。",
    from: "鲁米",
  },
  {
    en: "Stop acting so small. You are the universe in ecstatic motion.",
    zh: "别把自己活得那么小。你是宇宙在狂欢中的运行。",
    from: "鲁米",
  },
  {
    en: "Give me liberty, or give me death.",
    zh: "不自由，毋宁死。",
    from: "帕特里克·亨利",
  },
  {
    en: "The die is cast.",
    zh: "骰子已经掷出。",
    from: "凯撒",
  },
  {
    en: "Veni, vidi, vici.",
    zh: "我来，我见，我征服。",
    from: "凯撒",
  },
  {
    en: "Ships are safe in harbor, but that's not what ships are for.",
    zh: "船停在港里最安全，可船不是为此造的。",
    from: "谚语",
  },
  {
    en: "A smooth sea never made a skilled sailor.",
    zh: "平静的海，练不出好水手。",
    from: "谚语",
  },
  {
    en: "Fall seven times, stand up eight.",
    zh: "跌倒七次，第八次站起来。",
    from: "日本谚语",
  },
  {
    en: "The best time to plant a tree was twenty years ago. The second best time is now.",
    zh: "种树最好的时间是二十年前。其次就是现在。",
    from: "谚语",
  },
  {
    en: "Whether you think you can, or you think you can't — you're right.",
    zh: "你觉得自己行，或觉得不行——你都是对的。",
    from: "福特",
  },
  {
    en: "Knowing others is intelligence; knowing yourself is true wisdom.",
    zh: "知人者智，自知者明。",
    from: "老子",
  },
  {
    en: "The man who moves a mountain begins by carrying away small stones.",
    zh: "移山的人，是从搬走小石头开始的。",
    from: "谚语",
  },
  {
    en: "Still I rise.",
    zh: "可我依然升起。",
    from: "玛雅·安吉罗",
  },
  {
    en: "It's only after we've lost everything that we're free to do anything.",
    zh: "只有失去了一切，才自由得可以去做任何事。",
    from: "搏击俱乐部",
  },
  {
    en: "The things you own end up owning you.",
    zh: "你所占有的东西，最终会占有你。",
    from: "搏击俱乐部",
  },
  {
    en: "To be, or not to be, that is the question.",
    zh: "生存还是毁灭，这是一个问题。",
    from: "莎士比亚",
  },
  {
    en: "All the world's a stage, and all the men and women merely players.",
    zh: "世界是一座舞台，男男女女只是演员。",
    from: "莎士比亚",
  },
  {
    en: "This above all: to thine own self be true.",
    zh: "最要紧的是：对自己要诚实。",
    from: "莎士比亚",
  },
  {
    en: "Brevity is the soul of wit.",
    zh: "简洁是智慧的灵魂。",
    from: "莎士比亚",
  },
  {
    en: "There are more things in heaven and earth, Horatio, than are dreamt of in your philosophy.",
    zh: "天地间的事，霍拉旭，比你的哲学所能梦见的多得多。",
    from: "莎士比亚",
  },
  {
    en: "Shall I compare thee to a summer's day? Thou art more lovely and more temperate.",
    zh: "我能否把你比作夏日？你比它更可爱，也更温婉。",
    from: "莎士比亚",
  },
  {
    en: "Love looks not with the eyes, but with the mind.",
    zh: "爱不是用眼睛看，而是用心灵看。",
    from: "莎士比亚",
  },
  {
    en: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
    zh: "凡是有钱的单身汉，总要娶位太太，这是一条举世公认的真理。",
    from: "简·奥斯汀",
  },
  {
    en: "It was the best of times, it was the worst of times.",
    zh: "那是最好的时代，也是最坏的时代。",
    from: "狄更斯",
  },
  {
    en: "Please, sir, I want some more.",
    zh: "求求您，先生，我还想再要一点。",
    from: "狄更斯",
  },
  {
    en: "All animals are equal, but some animals are more equal than others.",
    zh: "所有动物一律平等，但有些动物比其他动物更平等。",
    from: "奥威尔",
  },
  {
    en: "In a time of deceit, telling the truth is a revolutionary act.",
    zh: "在谎言盛行的年代，说真话就是革命。",
    from: "奥威尔",
  },
  {
    en: "Who controls the past controls the future. Who controls the present controls the past.",
    zh: "谁控制过去，谁就控制未来；谁控制现在，谁就控制过去。",
    from: "奥威尔",
  },
  {
    en: "Government of the people, by the people, for the people, shall not perish from the earth.",
    zh: "民有、民治、民享的政府，不会从地球上消失。",
    from: "林肯",
  },
  {
    en: "With malice toward none, with charity for all.",
    zh: "对任何人不怀恶意，对所有人心存慈悲。",
    from: "林肯",
  },
  {
    en: "I have a dream that one day this nation will rise up and live out the true meaning of its creed.",
    zh: "我有一个梦想：有一天这个国家会奋起，真正实践它的立国信条。",
    from: "马丁·路德·金",
  },
  {
    en: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
    zh: "黑暗驱不走黑暗，只有光可以。仇恨驱不走仇恨，只有爱可以。",
    from: "马丁·路德·金",
  },
  {
    en: "The time is always right to do what is right.",
    zh: "做正确的事，任何时候都是合适的时候。",
    from: "马丁·路德·金",
  },
  {
    en: "Ask not what your country can do for you — ask what you can do for your country.",
    zh: "不要问国家能为你做什么，要问你能为国家做什么。",
    from: "肯尼迪",
  },
  {
    en: "We choose to go to the moon not because it is easy, but because it is hard.",
    zh: "我们选择登月，不是因为它容易，而是因为它困难。",
    from: "肯尼迪",
  },
  {
    en: "Imagination is more important than knowledge.",
    zh: "想象力比知识更重要。",
    from: "爱因斯坦",
  },
  {
    en: "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    zh: "人生像骑自行车：要保持平衡，就得一直往前。",
    from: "爱因斯坦",
  },
  {
    en: "Try not to become a man of success, but rather try to become a man of value.",
    zh: "别急着成为一个成功的人，先成为一个有价值的人。",
    from: "爱因斯坦",
  },
  {
    en: "Stay hungry. Stay foolish.",
    zh: "求知若饥，虚心若愚。",
    from: "乔布斯",
  },
  {
    en: "Your time is limited, so don't waste it living someone else's life.",
    zh: "你的时间有限，不要浪费在过别人的生活上。",
    from: "乔布斯",
  },
  {
    en: "We shall fight on the beaches, we shall fight on the landing grounds, we shall never surrender.",
    zh: "我们将在海滩作战，在登陆地作战，我们永不投降。",
    from: "丘吉尔",
  },
  {
    en: "People will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
    zh: "人们会忘记你说过什么、做过什么，但永远不会忘记你带给他们的感受。",
    from: "玛雅·安吉罗",
  },
  {
    en: "No one can make you feel inferior without your consent.",
    zh: "未经你同意，没人能让你觉得低人一等。",
    from: "埃莉诺·罗斯福",
  },
  {
    en: "The two most important days in your life are the day you are born and the day you find out why.",
    zh: "生命中最重要的两天：出生那天，和你明白为何而生那天。",
    from: "马克·吐温",
  },
  {
    en: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.",
    zh: "二十年后让你更遗憾的，不是做过的事，而是没做的事。",
    from: "马克·吐温",
  },
  {
    en: "We suffer more often in imagination than in reality.",
    zh: "我们在想象里受的苦，往往比现实更多。",
    from: "塞涅卡",
  },
  {
    en: "Luck is what happens when preparation meets opportunity.",
    zh: "幸运，是准备碰上了机会。",
    from: "塞涅卡",
  },
  {
    en: "It's not what happens to you, but how you react to it that matters.",
    zh: "要紧的不是遭遇了什么，而是你如何应对。",
    from: "爱比克泰德",
  },
  {
    en: "Don't explain your philosophy. Embody it.",
    zh: "不必解释你的哲学。活出来。",
    from: "爱比克泰德",
  },
  {
    en: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    zh: "我们重复做什么，就是什么。卓越不是一次举动，而是习惯。",
    from: "亚里士多德",
  },
  {
    en: "Knowing yourself is the beginning of all wisdom.",
    zh: "认识自己，是一切智慧的起点。",
    from: "亚里士多德",
  },
  {
    en: "The happiness of your life depends upon the quality of your thoughts.",
    zh: "人生幸不幸福，取决于念头的质量。",
    from: "马可·奥勒留",
  },
  {
    en: "When you arise in the morning, think of what a privilege it is to be alive.",
    zh: "早晨起来，先想想：活着本身就是一种特权。",
    from: "马可·奥勒留",
  },
  {
    en: "Become who you are.",
    zh: "成为你所是的那个人。",
    from: "尼采",
  },
  {
    en: "He who fights with monsters should look to it that he himself does not become a monster.",
    zh: "与怪物战斗的人，要当心自己也变成怪物。",
    from: "尼采",
  },
  {
    en: "Autumn is a second spring when every leaf is a flower.",
    zh: "秋天是第二个春天，每片叶子都是一朵花。",
    from: "加缪",
  },
  {
    en: "Be yourself; everyone else is already taken.",
    zh: "做你自己吧，别的角色都有人演了。",
    from: "王尔德",
  },
  {
    en: "Hope is the thing with feathers that perches in the soul.",
    zh: "希望是长着羽毛的东西，栖在灵魂里。",
    from: "狄金森",
  },
  {
    en: "A thing of beauty is a joy forever.",
    zh: "美的事物，是永恒的喜悦。",
    from: "济慈",
  },
  {
    en: "Beauty is truth, truth beauty.",
    zh: "美即是真，真即是美。",
    from: "济慈",
  },
  {
    en: "I wandered lonely as a cloud.",
    zh: "我孤独地漫游，像一朵云。",
    from: "华兹华斯",
  },
  {
    en: "To see a world in a grain of sand, and a heaven in a wild flower.",
    zh: "一粒沙里看见世界，一朵野花里看见天堂。",
    from: "布莱克",
  },
  {
    en: "Even the darkest night will end and the sun will rise.",
    zh: "再黑的夜也会结束，太阳总会升起。",
    from: "雨果",
  },
  {
    en: "Everyone thinks of changing the world, but no one thinks of changing himself.",
    zh: "人人都想改变世界，却没人想改变自己。",
    from: "托尔斯泰",
  },
  {
    en: "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.",
    zh: "真正的发现之旅，不在寻找新风景，而在拥有新的眼睛。",
    from: "普鲁斯特",
  },
  {
    en: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.",
    zh: "只有用心才能看得清楚；本质的东西，眼睛是看不见的。",
    from: "圣埃克苏佩里",
  },
  {
    en: "All grown-ups were once children — although few of them remember it.",
    zh: "所有大人都曾是小孩，虽然只有少数还记得。",
    from: "圣埃克苏佩里",
  },
  {
    en: "You are never too old to set another goal or to dream a new dream.",
    zh: "再年长，也可以再立一个目标，再做一个新梦。",
    from: "C.S. 刘易斯",
  },
  {
    en: "Go confidently in the direction of your dreams. Live the life you have imagined.",
    zh: "朝着梦想的方向自信地走。去过你想象过的那种生活。",
    from: "梭罗",
  },
  {
    en: "The mass of men lead lives of quiet desperation.",
    zh: "大多数人都过着安静的绝望生活。",
    from: "梭罗",
  },
  {
    en: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    zh: "不要只走现成的路，去没有路的地方，留下一条痕迹。",
    from: "爱默生",
  },
  {
    en: "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    zh: "身后与身前的事都很小，真正大的是我们内心。",
    from: "爱默生",
  },
  {
    en: "Life is either a daring adventure or nothing at all.",
    zh: "人生要么是一场大胆的冒险，要么什么都不是。",
    from: "海伦·凯勒",
  },
  {
    en: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.",
    zh: "世上最好、最美的东西，看不见也摸不着，只能用心去感受。",
    from: "海伦·凯勒",
  },
  {
    en: "An investment in knowledge pays the best interest.",
    zh: "投资知识，利息最高。",
    from: "富兰克林",
  },
  {
    en: "Tell me and I forget, teach me and I may remember, involve me and I learn.",
    zh: "告诉我，我会忘；教我，我也许记得；拉我一起做，我才真正学会。",
    from: "富兰克林",
  },
  {
    en: "The best way to predict the future is to create it.",
    zh: "预测未来最好的办法，就是去创造它。",
    from: "德鲁克",
  },
  {
    en: "I would rather have questions that can't be answered than answers that can't be questioned.",
    zh: "我宁愿要无法回答的问题，也不要不容置疑的答案。",
    from: "费曼",
  },
  {
    en: "We are a way for the cosmos to know itself.",
    zh: "我们是宇宙认识自己的一种方式。",
    from: "卡尔·萨根",
  },
  {
    en: "Don't Panic.",
    zh: "不要慌。",
    from: "银河系漫游指南",
  },
  {
    en: "It is good to have an end to journey toward; but it is the journey that matters, in the end.",
    zh: "有个要去的终点很好；可到头来，真正要紧的是这段路。",
    from: "勒古恩",
  },
  {
    en: "Once you've met someone, you never really forget them.",
    zh: "你一旦遇见过一个人，就再也不会真正忘记。",
    from: "千与千寻",
  },
  {
    en: "Always believe in yourself. Do this and no matter where you are, you will have nothing to fear.",
    zh: "永远相信自己。能做到这一点，无论在哪里都无所畏惧。",
    from: "天空之城",
  },
  {
    en: "Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.",
    zh: "昨天已成历史，明天还是谜，今天却是礼物。所以它叫 present。",
    from: "功夫熊猫",
  },
  {
    en: "Oh yes, the past can hurt. But the way I see it, you can either run from it, or learn from it.",
    zh: "是的，过去会痛。但依我看，你要么逃开它，要么从中学会。",
    from: "狮子王",
  },
  {
    en: "To infinity and beyond!",
    zh: "飞向宇宙，浩瀚无垠！",
    from: "玩具总动员",
  },
  {
    en: "Just keep swimming.",
    zh: "一直游下去。",
    from: "海底总动员",
  },
  {
    en: "The flower that blooms in adversity is the most rare and beautiful of all.",
    zh: "逆境中绽放的花，才是最稀有、最美的。",
    from: "花木兰",
  },
  {
    en: "That's one small step for a man, one giant leap for mankind.",
    zh: "这是一个人的一小步，却是人类的一大步。",
    from: "阿姆斯特朗",
  },
  {
    en: "The only thing we have to fear is fear itself.",
    zh: "我们唯一需要害怕的，就是害怕本身。",
    from: "罗斯福",
  },
  {
    en: "I think, therefore I am.",
    zh: "我思故我在。",
    from: "笛卡尔",
  },
  {
    en: "Knowledge is power.",
    zh: "知识就是力量。",
    from: "培根",
  },
  {
    en: "Reading makes a full man; conference a ready man; and writing an exact man.",
    zh: "读书使人充实，讨论使人机智，笔记使人准确。",
    from: "培根",
  },
  {
    en: "Some books are to be tasted, others to be swallowed, and some few to be chewed and digested.",
    zh: "有些书只需浅尝，有些可以吞咽，少数则需细嚼慢咽。",
    from: "培根",
  },
  {
    en: "The only true wisdom is in knowing you know nothing.",
    zh: "真正的智慧，是知道自己一无所知。",
    from: "苏格拉底",
  },
  {
    en: "I cannot teach anybody anything. I can only make them think.",
    zh: "我教不了任何人任何东西。我只能促使他们思考。",
    from: "苏格拉底",
  },
  {
    en: "Man is the measure of all things.",
    zh: "人是万物的尺度。",
    from: "普罗泰戈拉",
  },
  {
    en: "The only thing I know is that I know nothing.",
    zh: "我唯一知道的，就是我一无所知。",
    from: "苏格拉底",
  },
  {
    en: "Plato is dear to me, but dearer still is truth.",
    zh: "吾爱吾师，吾更爱真理。",
    from: "亚里士多德",
  },
  {
    en: "Happiness depends upon ourselves.",
    zh: "幸福取决于我们自己。",
    from: "亚里士多德",
  },
  {
    en: "Educating the mind without educating the heart is no education at all.",
    zh: "只教头脑、不教心灵，根本不算教育。",
    from: "亚里士多德",
  },
  {
    en: "Follow your bliss.",
    zh: "追随让你充满生命力的事。",
    from: "约瑟夫·坎贝尔",
  },
  {
    en: "So we beat on, boats against the current, borne back ceaselessly into the past.",
    zh: "于是我们奋力向前，逆水行舟，不停被浪潮推回过去。",
    from: "菲茨杰拉德",
  },
  {
    en: "There are only the pursued, the pursuing, the busy and the tired.",
    zh: "世上只有被追的人、追人的人、忙碌的人和疲倦的人。",
    from: "菲茨杰拉德",
  },
  {
    en: "You can't repeat the past.",
    zh: "你无法重复过去。",
    from: "菲茨杰拉德",
  },
  {
    en: "Even the smallest person can change the course of the future.",
    zh: "再渺小的人，也能改变未来的走向。",
    from: "托尔金",
  },
  {
    en: "It is not our abilities that show what we truly are. It is our choices.",
    zh: "真正说明我们是谁的，不是能力，而是选择。",
    from: "J.K. 罗琳",
  },
  {
    en: "It does not do to dwell on dreams and forget to live.",
    zh: "沉溺于梦想而忘了生活，可不好。",
    from: "J.K. 罗琳",
  },
  {
    en: "Education is the most powerful weapon which you can use to change the world.",
    zh: "教育是你能用来改变世界的最有力武器。",
    from: "曼德拉",
  },
  {
    en: "A person who never made a mistake never tried anything new.",
    zh: "从不犯错的人，也从未尝试过新事物。",
    from: "爱因斯坦",
  },
  {
    en: "Logic will get you from A to B. Imagination will take you everywhere.",
    zh: "逻辑能把你从 A 带到 B。想象力能带你去任何地方。",
    from: "爱因斯坦",
  },
  {
    en: "The important thing is not to stop questioning.",
    zh: "重要的是，不要停止发问。",
    from: "爱因斯坦",
  },
  {
    en: "If you want to live a happy life, tie it to a goal, not to people or things.",
    zh: "想过幸福的生活，就把自己系在目标上，而不是人或物上。",
    from: "爱因斯坦",
  },
  {
    en: "Simplicity is the ultimate sophistication.",
    zh: "简洁是最高级的复杂。",
    from: "达·芬奇",
  },
  {
    en: "Learning never exhausts the mind.",
    zh: "学习从不会让心灵枯竭。",
    from: "达·芬奇",
  },
  {
    en: "The noblest pleasure is the joy of understanding.",
    zh: "最高贵的快乐，是理解的喜悦。",
    from: "达·芬奇",
  },
  {
    en: "Well done is better than well said.",
    zh: "做好，胜过说好。",
    from: "富兰克林",
  },
  {
    en: "Lost time is never found again.",
    zh: "失去的时间，再也找不回来。",
    from: "富兰克林",
  },
  {
    en: "Energy and persistence conquer all things.",
    zh: "精力与坚持，能征服一切。",
    from: "富兰克林",
  },
  {
    en: "Do what you can, with what you have, where you are.",
    zh: "在你所在之处，用你所有，做你所能。",
    from: "西奥多·罗斯福",
  },
  {
    en: "Believe you can and you're halfway there.",
    zh: "相信自己能做到，你就已经走完一半。",
    from: "西奥多·罗斯福",
  },
  {
    en: "It is hard to fail, but it is worse never to have tried to succeed.",
    zh: "失败很难受，但从未尝试去成功更糟。",
    from: "西奥多·罗斯福",
  },
  {
    en: "The only way to do great work is to love what you do.",
    zh: "做出伟大工作的唯一办法，是热爱你所做的事。",
    from: "乔布斯",
  },
  {
    en: "Innovation distinguishes between a leader and a follower.",
    zh: "创新，区分了引领者与跟随者。",
    from: "乔布斯",
  },
  {
    en: "Have the courage to follow your heart and intuition.",
    zh: "要有勇气追随自己的内心和直觉。",
    from: "乔布斯",
  },
  {
    en: "Coming together is a beginning; keeping together is progress; working together is success.",
    zh: "聚在一起是开始；保持在一起是进步；一起做事才是成功。",
    from: "亨利·福特",
  },
  {
    en: "Quality means doing it right when no one is looking.",
    zh: "质量，是没人看着时仍然做对。",
    from: "亨利·福特",
  },
  {
    en: "I have not failed. I've just found 10,000 ways that won't work.",
    zh: "我没有失败。我只是找到了一万种行不通的办法。",
    from: "爱迪生",
  },
  {
    en: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    zh: "天才是百分之一的灵感，加上百分之九十九的汗水。",
    from: "爱迪生",
  },
  {
    en: "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
    zh: "机会常被错过，因为它穿着工装，看起来像干活。",
    from: "爱迪生",
  },
  {
    en: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
    zh: "悲观者在每个机会里看见困难；乐观者在每个困难里看见机会。",
    from: "丘吉尔",
  },
  {
    en: "To improve is to change; to be perfect is to change often.",
    zh: "要进步就得改变；要近于完美，就得常常改变。",
    from: "丘吉尔",
  },
  {
    en: "Never confuse a single defeat with a final defeat.",
    zh: "不要把一次挫败，当成最终的失败。",
    from: "菲茨杰拉德",
  },
  {
    en: "There is nothing to writing. All you do is sit down at a typewriter and bleed.",
    zh: "写作没什么。你只要坐在打字机前，把血放出来。",
    from: "海明威",
  },
  {
    en: "Courage is grace under pressure.",
    zh: "勇气，是压力下的从容。",
    from: "海明威",
  },
  {
    en: "There is no friend as loyal as a book.",
    zh: "没有比书更忠诚的朋友。",
    from: "海明威",
  },
  {
    en: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    zh: "生命最大的荣耀，不在从不跌倒，而在每次跌倒后再站起来。",
    from: "曼德拉",
  },
  {
    en: "If you judge people, you have no time to love them.",
    zh: "如果你总在评判别人，就没有时间去爱他们。",
    from: "特蕾莎修女",
  },
  {
    en: "Spread love everywhere you go.",
    zh: "你走到哪里，就把爱带到哪里。",
    from: "特蕾莎修女",
  },
  {
    en: "Kindness is a language which the deaf can hear and the blind can see.",
    zh: "善意是一种聋者能听见、盲者能看见的语言。",
    from: "马克·吐温",
  },
  {
    en: "The secret of getting ahead is getting started.",
    zh: "领先的秘诀，就是先开始。",
    from: "马克·吐温",
  },
  {
    en: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    zh: "每当你发现自己站在多数一边，就该停下来想想。",
    from: "马克·吐温",
  },
  {
    en: "What we think, we become.",
    zh: "我们思其所思，终成其所成。",
    from: "佛陀",
  },
  {
    en: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    zh: "不要住在过去，不要梦见未来，把心安在此刻。",
    from: "佛陀",
  },
  {
    en: "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened.",
    zh: "一枝烛火能点亮千万枝，自身的光却不会因此缩短。",
    from: "佛陀",
  },
  {
    en: "A journey of a thousand miles begins with a single step.",
    zh: "千里之行，始于足下。",
    from: "老子",
  },
  {
    en: "Nature does not hurry, yet everything is accomplished.",
    zh: "天地不匆忙，而万事自成。",
    from: "老子",
  },
  {
    en: "Real knowledge is to know the extent of one's ignorance.",
    zh: "真正的知识，是知道自己无知到什么程度。",
    from: "孔子",
  },
  {
    en: "It does not matter how slowly you go as long as you do not stop.",
    zh: "走得慢没关系，只要不停就好。",
    from: "孔子",
  },
  {
    en: "Wherever you go, go with all your heart.",
    zh: "无论去哪里，都要全心全意地去。",
    from: "孔子",
  },
  {
    en: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
    zh: "读得越多，知道的就越多；学得越多，能去的地方就越多。",
    from: "苏斯博士",
  },
  {
    en: "Why fit in when you were born to stand out?",
    zh: "你生来就是要出众的，何必去合群？",
    from: "苏斯博士",
  },
  {
    en: "Today you are you, that is truer than true.",
    zh: "今天的你就是你，这比什么都更真。",
    from: "苏斯博士",
  },
  {
    en: "It's not the years in your life that count. It's the life in your years.",
    zh: "要紧的不是生命里有多少年，而是那些年里有多少生命。",
    from: "林肯",
  },
  {
    en: "Whatever you are, be a good one.",
    zh: "无论你是什么，都做好那一个。",
    from: "林肯",
  },
  {
    en: "The future belongs to those who believe in the beauty of their dreams.",
    zh: "未来属于那些相信梦想之美的人。",
    from: "埃莉诺·罗斯福",
  },
  {
    en: "Do one thing every day that scares you.",
    zh: "每天做一件让你害怕的事。",
    from: "埃莉诺·罗斯福",
  },
  {
    en: "You must do the things you think you cannot do.",
    zh: "你必须去做那些你以为自己做不到的事。",
    from: "埃莉诺·罗斯福",
  },
  {
    en: "Great things are done by a series of small things brought together.",
    zh: "伟大的事，是由一连串小事聚成的。",
    from: "梵高",
  },
  {
    en: "I am seeking. I am striving. I am in it with all my heart.",
    zh: "我在寻找，我在努力，我全心投入其中。",
    from: "梵高",
  },
  {
    en: "If you hear a voice within you say you cannot paint, then by all means paint, and that voice will be silenced.",
    zh: "若内心有个声音说你不会画，那就尽管去画，那声音自会沉默。",
    from: "梵高",
  },
  {
    en: "Art is never finished, only abandoned.",
    zh: "艺术从未完成，只是被放下。",
    from: "达·芬奇",
  },
  {
    en: "Every artist was first an amateur.",
    zh: "每个艺术家，起初都是业余的。",
    from: "爱默生",
  },
  {
    en: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    zh: "在一个不断要把你变成别人的世界里，做自己就是最大的成就。",
    from: "爱默生",
  },
  {
    en: "Write it on your heart that every day is the best day in the year.",
    zh: "把这句话写在心里：每一天都是一年中最好的一天。",
    from: "爱默生",
  },
  {
    en: "The only person you are destined to become is the person you decide to be.",
    zh: "你注定要成为的，只有你决定成为的那个人。",
    from: "爱默生",
  },
  {
    en: "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
    zh: "多好啊：没人需要等哪怕一刻，才能开始让世界更好一点。",
    from: "安妮·弗兰克",
  },
  {
    en: "Think of all the beauty still left around you and be happy.",
    zh: "想想身边还剩多少美，然后快乐起来。",
    from: "安妮·弗兰克",
  },
  {
    en: "Whoever is happy will make others happy too.",
    zh: "谁快乐，谁就能让别人也快乐。",
    from: "安妮·弗兰克",
  },
  {
    en: "It is never too late to be what you might have been.",
    zh: "成为本可以成为的自己，永远都不晚。",
    from: "乔治·艾略特",
  },
  {
    en: "What do we live for, if it is not to make life less difficult for each other?",
    zh: "若不是为了让彼此的生活轻松一点，我们活着又为了什么？",
    from: "乔治·艾略特",
  },
  {
    en: "Two roads diverged in a wood, and I — I took the one less traveled by.",
    zh: "林中分出两条路，而我——我选择了人迹更少的一条。",
    from: "罗伯特·弗罗斯特",
  },
];

function hash(input: string): number {
  let h = 2166136261;
  for (let i = 0; i < input.length; i += 1) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function getDailyLearn(now = new Date()) {
  const day = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Shanghai",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(now);
  const poem = DAILY_POEMS[hash(`poem:${day}`) % DAILY_POEMS.length];
  const sentence = DAILY_SENTENCES[hash(`en:${day}`) % DAILY_SENTENCES.length];
  return { day, poem, sentence };
}

function pickUnseen<T>(items: T[], seen: Set<string>, key: (item: T) => string, current: T): T {
  const unused = items.filter((item) => !seen.has(key(item)));
  const pool = unused.length ? unused : items.filter((item) => key(item) !== key(current));
  if (!pool.length) return current;
  if (!unused.length) seen.clear();
  const next = pool[Math.floor(Math.random() * pool.length)];
  seen.add(key(next));
  return next;
}

export function shuffleLearn(
  current: { poem: DailyPoem; sentence: DailySentence },
  seen?: { poems: Set<string>; sentences: Set<string> },
) {
  const poems = seen?.poems ?? new Set([current.poem.line]);
  const sentences = seen?.sentences ?? new Set([current.sentence.en]);
  poems.add(current.poem.line);
  sentences.add(current.sentence.en);
  return {
    poem: pickUnseen(DAILY_POEMS, poems, (item) => item.line, current.poem),
    sentence: pickUnseen(DAILY_SENTENCES, sentences, (item) => item.en, current.sentence),
  };
}
